### Basic Convolutional Neural Networks 

### Convolution: tf.nn.conv2d(input, filter, strides, padding, ...)
input: 輸入圖像, shape: [batch, in_height, in_width, in_channels]
       -> [batch圖片數量, 圖片高度, 圖片寬度, 圖片通道數]
       
filter: 過濾器(convolution kernel), shape: [filter_height, filter_width, in_channels, out_channels]
        -> [卷積核的高度，卷積核的宽度，圖片通道數，卷積核個數]
        
strides: 過濾器移動的格子數，一般shape:[1，長上步長，寬上步長，1]，想像過濾器移動步數，如長上步長=2，寬上步長=1，則過濾器向長邊每移動兩格，向寬邊每移動一格。

padding: "SAME"-> 以過濾器中心與圖片剛接觸開始做計算。
         "VALID"-> 過濾器在圖片裡開始做計算。
         這兩種不同模式是對過濾器移動範圍有不同的限制。

Reference:

https://blog.csdn.net/leviopku/article/details/80327478

https://ithelp.ithome.com.tw/articles/10187424

<img src="Pictures/x&w.PNG">

In [1]:
# example(fixed strides=[1,1,1,1]):
import tensorflow as tf
# image: shape(x)=(2,4,4,1)
x = tf.constant([[[1.0,2.0,3.0,4.0],
                  [5.0,6.0,7.0,8.0],
                  [8.0,7.0,6.0,5.0],
                  [4.0,3.0,2.0,1.0]],
                 [[4.0,3.0,2.0,1.0],
                  [8.0,7.0,6.0,5.0],
                  [1.0,2.0,3.0,4.0],
                  [5.0,6.0,7.0,8.0]]], dtype=tf.float32)
x = tf.reshape(x, [2,4,4,1])

# filter: shape(W)=(2,2,1,1)
W2x2 = tf.constant([[1, 1], [0, 1]], dtype=tf.float32)
W2x2 = tf.reshape(W2x2, [2,2,1,1])
conv_same2x2 = tf.nn.conv2d(x, W2x2, strides=[1,1,1,1], padding='SAME')
conv_valid2x2 = tf.nn.conv2d(x, W2x2, strides=[1,1,1,1], padding='VALID')

# filter: shape(W)=(3,3,1,1)
W3x3 = tf.constant([[1, 0, 1], [0, 1, 0], [1, 0, 1]], dtype=tf.float32)
W3x3 = tf.reshape(W3x3, [3,3,1,1])
conv_same3x3 = tf.nn.conv2d(x, W3x3, strides=[1,1,1,1], padding='SAME')
conv_valid3x3 = tf.nn.conv2d(x, W3x3, strides=[1,1,1,1], padding='VALID')

# filter: shape(W)=(4,4,1,1)
W4x4 = tf.constant([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]], dtype=tf.float32)
W4x4 = tf.reshape(W4x4, [4,4,1,1])
conv_same4x4 = tf.nn.conv2d(x, W4x4, strides=[1,1,1,1], padding='SAME')
conv_valid4x4 = tf.nn.conv2d(x, W4x4, strides=[1,1,1,1], padding='VALID')

In [2]:
# W2x2
with tf.Session() as sess:
    same, valid = sess.run([conv_same2x2, conv_valid2x2])
    print("SAME:", same)
    print("VALID:", valid)
    print("SAME shape:", same.shape)
    print("VALID shape:", valid.shape)

SAME: [[[[ 9.]
   [12.]
   [15.]
   [ 4.]]

  [[18.]
   [19.]
   [20.]
   [ 8.]]

  [[18.]
   [15.]
   [12.]
   [ 5.]]

  [[ 7.]
   [ 5.]
   [ 3.]
   [ 1.]]]


 [[[14.]
   [11.]
   [ 8.]
   [ 1.]]

  [[17.]
   [16.]
   [15.]
   [ 5.]]

  [[ 9.]
   [12.]
   [15.]
   [ 4.]]

  [[11.]
   [13.]
   [15.]
   [ 8.]]]]
VALID: [[[[ 9.]
   [12.]
   [15.]]

  [[18.]
   [19.]
   [20.]]

  [[18.]
   [15.]
   [12.]]]


 [[[14.]
   [11.]
   [ 8.]]

  [[17.]
   [16.]
   [15.]]

  [[ 9.]
   [12.]
   [15.]]]]
SAME shape: (2, 4, 4, 1)
VALID shape: (2, 3, 3, 1)


圖解:
<img src="Pictures/w2x2.PNG" style="width:800px;height:300px;">

In [3]:
# W3x3
with tf.Session() as sess:
    same, valid = sess.run([conv_same3x3, conv_valid3x3])
    print("SAME:", same)
    print("VALID:", valid)
    print("SAME shape:", same.shape)
    print("VALID shape:", valid.shape)

SAME: [[[[ 7.]
   [14.]
   [17.]
   [11.]]

  [[14.]
   [24.]
   [25.]
   [17.]]

  [[17.]
   [25.]
   [24.]
   [14.]]

  [[11.]
   [17.]
   [14.]
   [ 7.]]]


 [[[11.]
   [17.]
   [14.]
   [ 7.]]

  [[13.]
   [17.]
   [16.]
   [10.]]

  [[14.]
   [28.]
   [29.]
   [17.]]

  [[ 7.]
   [10.]
   [13.]
   [11.]]]]
VALID: [[[[24.]
   [25.]]

  [[25.]
   [24.]]]


 [[[17.]
   [16.]]

  [[28.]
   [29.]]]]
SAME shape: (2, 4, 4, 1)
VALID shape: (2, 2, 2, 1)


圖解:
<img src="Pictures/w3x3.PNG" style="width:800px;height:300px;">

In [4]:
# W4x4
with tf.Session() as sess:
    same, valid = sess.run([conv_same4x4, conv_valid4x4])
    print("SAME:", same)
    print("VALID:", valid)
    print("SAME shape:", same.shape)
    print("VALID shape:", valid.shape)

SAME: [[[[13.]
   [14.]
   [11.]
   [ 4.]]

  [[14.]
   [14.]
   [14.]
   [11.]]

  [[11.]
   [14.]
   [13.]
   [12.]]

  [[ 4.]
   [11.]
   [ 9.]
   [ 7.]]]


 [[[14.]
   [13.]
   [ 7.]
   [ 1.]]

  [[17.]
   [22.]
   [13.]
   [ 7.]]

  [[ 7.]
   [17.]
   [18.]
   [10.]]

  [[ 5.]
   [ 7.]
   [ 9.]
   [11.]]]]
VALID: [[[[14.]]]


 [[[22.]]]]
SAME shape: (2, 4, 4, 1)
VALID shape: (2, 1, 1, 1)


圖解:
<img src="Pictures/w4x4.PNG" style="width:800px;height:300px;">

### Pooling: tf.nn.max_pool(value, ksize, strides, padding, ...)

value: 需要池化的陣列, shape: [batch, height, width, channels]

ksize: 池化窗口的大小，一般shape是[1, height, width, 1]
       (一般不會在batch和channels做pool)

strides: 過濾器移動的格子數。

padding: 與tf.nn.conv2d的padding一致。

max_pool為過濾器每掃池化陣列的最大數值，即取陣列中重要的部份。

Reference:

https://blog.csdn.net/mao_xiao_feng/article/details/53453926

In [17]:
# example
import tensorflow as tf
 
x = tf.constant([[[1.0,2.0,3.0,4.0],
                  [5.0,6.0,7.0,8.0],
                  [8.0,7.0,6.0,5.0],
                  [4.0,3.0,2.0,1.0]],
                 [[4.0,3.0,2.0,1.0],
                  [8.0,7.0,6.0,5.0],
                  [1.0,2.0,3.0,4.0],
                  [5.0,6.0,7.0,8.0]]])
x = tf.reshape(x, [2,4,4,1])

VALID_pooling = tf.nn.max_pool(x, ksize=[1,2,2,1], strides=[1,1,1,1], padding='VALID')
SAME_pooling = tf.nn.max_pool(x, ksize=[1,2,2,1], strides=[1,1,1,1], padding='SAME')

with tf.Session() as sess:
    VALID, SAME = sess.run([VALID_pooling, SAME_pooling])
    print('x:', sess.run(x))
    print("VALID:", VALID)
    print("VALID shape:", VALID.shape)
    print("SAME:", SAME)
    print("SAME shape:", SAME.shape)

x: [[[[1.]
   [2.]
   [3.]
   [4.]]

  [[5.]
   [6.]
   [7.]
   [8.]]

  [[8.]
   [7.]
   [6.]
   [5.]]

  [[4.]
   [3.]
   [2.]
   [1.]]]


 [[[4.]
   [3.]
   [2.]
   [1.]]

  [[8.]
   [7.]
   [6.]
   [5.]]

  [[1.]
   [2.]
   [3.]
   [4.]]

  [[5.]
   [6.]
   [7.]
   [8.]]]]
VALID: [[[[6.]
   [7.]
   [8.]]

  [[8.]
   [7.]
   [8.]]

  [[8.]
   [7.]
   [6.]]]


 [[[8.]
   [7.]
   [6.]]

  [[8.]
   [7.]
   [6.]]

  [[6.]
   [7.]
   [8.]]]]
VALID shape: (2, 3, 3, 1)
SAME: [[[[6.]
   [7.]
   [8.]
   [8.]]

  [[8.]
   [7.]
   [8.]
   [8.]]

  [[8.]
   [7.]
   [6.]
   [5.]]

  [[4.]
   [3.]
   [2.]
   [1.]]]


 [[[8.]
   [7.]
   [6.]
   [5.]]

  [[8.]
   [7.]
   [6.]
   [5.]]

  [[6.]
   [7.]
   [8.]
   [8.]]

  [[6.]
   [7.]
   [8.]
   [8.]]]]
SAME shape: (2, 4, 4, 1)


圖解：
<img src="Pictures/pooling.png" style="width:800px;height:300px;">

In [ ]:
# https://morvanzhou.github.io/tutorials/machine-learning/tensorflow/5-05-CNN3/
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
# number 1 to 10 data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

In [ ]:
def weight_variable(shape):
    # Truncated normal distribution: https://en.wikipedia.org/wiki/Truncated_normal_distribution
    initial = tf.truncated_normal(shape, mean=0.5, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)

def conv2d(x, W):
    # Convolution
    return tf.nn.conv2d(x, W, strides=[1,1,1,1], padding='SAME')

def max_pool_2x2(x):
    # Pooling
    return tf.nn.max_pool(x, ksize=[1,2,2,1], strides=[1,1,1,1], padding='SAME')

In [ ]:
# define placeholder for inputs to network

