In [1]:
# import numpy package
import numpy as np

In [2]:
# np.random
# random in standard normal distribution
arr1 = np.random.randn(2,4)
print(arr1)

# random in (0, 1)
arr2 = np.random.rand(2,4)
print(arr2)

[[ 1.64537945  2.45372374  0.18036015 -0.42195895]
 [-0.87510784 -0.72371626  0.85067298 -0.56412277]]
[[0.10705993 0.51225556 0.5923479  0.71160963]
 [0.30130823 0.33753395 0.45099584 0.61695974]]


In [57]:
# np.shuffle
arr = np.array([1,2,3,4,5])
print(arr)
np.random.shuffle(arr)
print(arr)

[1 2 3 4 5]
[1 5 3 4 2]


In [20]:
# np.empty
# unlike zeros, does not set the array values to zero, and may therefore be marginally faster.
empty = np.empty([2,4])
print(empty) #random
print(empty.shape)

# np.zeros
zeros = np.zeros((3, 1))
print(zeros)
print(zeros.shape)

# np.ones
ones_1 = np.ones((3, 1))
print(ones_1)
print(ones_1.shape)

ones_2 = np.ones((3, 2))
print(ones_2)
print(ones_2.shape)

[[0.10705993 0.51225556 0.5923479  0.71160963]
 [0.30130823 0.33753395 0.45099584 0.61695974]]
(2, 4)
[[0.]
 [0.]
 [0.]]
(3, 1)
[[1.]
 [1.]
 [1.]]
(3, 1)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2)


In [30]:
# np.concatenate
# numpy.concatenate((a1,a2,...), axis=0), a1, a2, ...
a = np.array([1,2,3])
b = np.array([11,22,33])
c = np.array([44,55,66])
print(np.concatenate((a,b,c)))

d = np.array([[1,2,3], [4,5,6]])
e = np.array([[7,8,9], [9,8,7]])
print(np.concatenate((d, e), axis=0)) # 表示對應列的數组進行拼接
print(np.concatenate((d, e), axis=1)) # 表示對應行的數组進行拼接

[ 1  2  3 11 22 33 44 55 66]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]]
[[1 2 3 7 8 9]
 [4 5 6 9 8 7]]


In [37]:
# dot
a = np.array([[1,0,2], [0,1,1]]) 
b = np.array([[0,2,0], [1,1,3]]).T
print(a.shape)
print(b.shape)

# c=a*b
c = a.dot(b)
print(c)

(2, 3)
(3, 2)
[[0 7]
 [2 4]]
